### ISSUE TITLE
How to use inlineCxxPlugin in other packages?

### ISSUE THREAD

**Issue by dirkschumacher** [coatless/rcppensmallen#12]
Maybe I don't understand the plugin system, but shouldn't `inlineCxxPlugin` be exported in order for other packages to use it?

**Comment by coatless** [comment]
Surprisingly, no. 
This is handled nicely in the plugin search: 

https://github.com/RcppCore/Rcpp/blob/4ec861775601ab9c6fcad3fd03d4b84ba88814b5/R/Attributes.R#L69-L90

https://github.com/RcppCore/Rcpp/blob/4ec861775601ab9c6fcad3fd03d4b84ba88814b5/R/inline.R#L18-L56


The `RcppEnsmallen` variant is similar to the `RcppArmadillo` variant:

https://github.com/RcppCore/RcppArmadillo/blob/188beeae47cf354c4b00d8fdcdf6ec7255d36f92/R/inline.R#L18-L31

**Comment by dirkschumacher** [comment]
Thanks
