### ISSUE TITLE
Package usage error - RcppExports includes Rcpp and RcppArmadillo

### ISSUE THREAD

**Issue by ryurko** [coatless/rcppensmallen#19]
Thank you for creating a great package that is easy to use. However, when creating a `R` package with `RcppEnsmallen` I am encountering an error that I'm not sure how to address. In the RcppExports.cpp file there are include statements for both `Rcpp` and `RcppArmadillo`, which is leading to the error "`Do not include either 'Rcpp.h' or 'RcppArmadillo.h'. Please only use 'RcppEnsmallen.h'`." Because the RcppExports.cpp file is generated by the `Rcpp::compileAttributes()` function I am not sure how to correct this. This is only an issue I've encountered when creating a package, not when running individual script files via `Rcpp::sourceCpp()`.

I am a beginner to using `Rcpp` so there might be something simple that I am missing. I use `devtools` and RStudio for creating packages, and from my understanding `devtools::document()`, as well as the RStudio package build/reload tools, automatically calls the `Rcpp::compileAttributes()` function. My .cpp file containing functions only begins with the following: 

```
#include <RcppEnsmallen.h>
#include <RcppArmadilloExtensions/sample.h>

// [[Rcpp::plugins("cpp11")]]

// [[Rcpp::depends(RcppEnsmallen)]]

using namespace Rcpp;

```
In my use of `RcppEnsmallen` by just calling `Rcpp::sourceCpp()` on scripts rather than developing a package, I do not encounter any errors. I'm not sure what is the proper way to address the RcppExports file however.

Any help would be greatly appreciated, I look forward to continue to use `RcppEnsmallen` in my research.

**Comment by coatless** [comment]
@ryurko packages are slightly different then standalone scripts. Rcpp Attributes (plugins and depends) are used when developing the standalone scripts.

In the case of an _R_ package, you need to modify the `DESCRIPTION` file. Details at:
https://cran.r-project.org/web/packages/RcppEnsmallen/vignettes/using-rcppensmallen.html#package-usage

In particular, the `DESCRIPTION` file requires the `LinkingTo` field to contain:

```bash
LinkingTo: Rcpp, RcppArmadillo (>= 0.8.400.0.0), RcppEnsmallen (>= 0.2.10.0.1)
```

Next, the `src/` directory must contain both a `Makevars` and `Makevars.win`  file with:

```bash
CXX_STD = CXX11
PKG_CXXFLAGS = $(SHLIB_OPENMP_CXXFLAGS)
PKG_LIBS = $(SHLIB_OPENMP_CXXFLAGS) $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)
```

**Comment by ryurko** [comment]
Thanks for the fast reponse, but yes I should've included that I followed the steps at the end of the vignette with the `LinkingTo` field in the `DESCRIPTION` file, as well as the `Makevars` and `Makevars.win ` files including those lines. However when I attempt to run the `devtools::document() `function I get the error still due to RcppExports.cpp including:

```
#include <RcppArmadillo.h>
#include <RcppEnsmallen.h>
#include <Rcpp.h>
```
which I know it shouldn't, but from my understanding I can't modify the RcppExports.cpp file.

**Comment by eddelbuettel** [comment]
Interesting issue and likely bug.  We may be overeager in the package skeleton generator.  Try maybe removing Rcpp from LinkingTo and see if it helps -- it is a guess at this point.  I don't have time right now to dig what drives the list of includes added by the code generator.

**Comment by ryurko** [comment]
I removed Rcpp but it was still in the resulting RcppExports file, but results in a different error:
```
In file included from /Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include/RcppArmadillo.h:31:
/Library/Frameworks/R.framework/Versions/3.5/Resources/library/RcppArmadillo/include/RcppArmadilloForward.h:26:10: fatal error: 'RcppCommon.h' file not found
#include <RcppCommon.h>
         ^~~~~~~~~~~~~~
```
I then tried removing the RcppArmadillo (with or without Rcpp in LinkingTo) and it returns a similar error but with 'RcppArmadillo.h' not found. 

Just for sanity I made a separate package using the RStudio 'R Package using RcppArmadillo' option for the project, with only the exact same linear regression file as the vignette mentioned above but the same error remains. This is probably a very naive question, but why is it an error that that those include statements are in the RcppExports.cpp file? Because when I build the example `RcppArmadillo` package using the above RStudio command there is no error, yet its resulting RcppExports.cpp file includes both include statements: 
```
#include <RcppArmadillo.h>
#include <Rcpp.h>
```
while `RcppArmadillo` throws an error if the line `#include <Rcpp.h>` is in other .cpp scripts. Is this potentially not actually an error then? Again my understanding of Rcpp is very much beginner level, just hoping to assist in any way I can.

**Comment by eddelbuettel** [comment]
I noodled with it a little bit earlier and I have no good immediate answer.  Every 'LinkingTo:' leads to in `#include`, and we worked it out between Rcpp and RcppArmadillo.

Enter RcppEnsmallen. That is, for now, an unsolved issue. I'd (as much as it sucks) edit RcppExports.cpp by hand.  We need to think through this and there are no easy answers.  Maybe some #define-if-notdefined games. To be seen...

**Comment by eddelbuettel** [comment]
Rcpp in its closed issues has a few related tickets:
- non-cooperating packages https://github.com/RcppCore/Rcpp/issues/808
- cooperating packages where reordering / declarations helped (maybe a model here?) https://github.com/RcppCore/Rcpp/issues/550

**Comment by ryurko** [comment]
Ok thank you for the information and relevant links. I'll reply if I come up with a potential workaround or (somehow) a solution.

**Comment by eddelbuettel** [comment]
It is an oddly complicated issue.  I guess for RcppArmadillo and Rcpp we "got by" thanks to the lexicographics sorting and RcppArmadillo taking care of it.  One of the reference points to RcppMLPACK2 (also us, and also around Rcpp + RcppArmadillo) but I no longer remember what I did. 

We definitely had an issue with RcppArmadillo needing this with respect to Rcpp; I just don't know about RcppEnsmallen which I have used less myself.   

On thing I just tried on a lark, and which you may copy, is to simply not enforce the error biting you here:

```diff
Unstaged changes (1)
modified   inst/include/RcppEnsmallen.h
@@ -18,9 +18,9 @@
 #ifndef RcppEnsmallen__RcppEnsmallen__h
 #define RcppEnsmallen__RcppEnsmallen__h
 
-#if defined(Rcpp_hpp) && defined(RcppArmadillo__RcppArmadillo__h)
-#error "Do not include either 'Rcpp.h' or 'RcppArmadillo.h'. Please only use 'RcppEnsmallen.h'."
-#endif
+//#if defined(Rcpp_hpp) && defined(RcppArmadillo__RcppArmadillo__h)
+//#error "Do not include either 'Rcpp.h' or 'RcppArmadillo.h'. Please only use 'RcppEnsmallen.h'."
+//#endif
 
 // Enable RcppArmadillo and Rcpp
 #include <RcppArmadillo.h>

```

Maybe give that a shot and report back?

**Comment by eddelbuettel** [comment]
I committed a slightly refined version that omits the test (and potentially fatal `#error`) unless and opt-in variable / compile flag is set, and made that pr #19.  @coatless to review.

**Comment by ryurko** [comment]
After commenting out the error check everything appears to be working fine without warnings, both the example package I created (just using the linear regression code example from the RcppEnsmallen vignette) as well as my other package in development. 

Thanks for the quick assistance! I'll reply back if there's any odd behavior that follows, or if I figure something else out as I learn more about what's going on.

**Comment by coatless** [comment]
@ryurko newest build should be on CRAN shortly.

**Comment by coatless** [comment]
@ryurko on CRAN now!

https://cran.r-project.org/package=RcppEnsmallen

**Comment by ryurko** [comment]
Great thanks!
